### ISSUE TITLE
Subtract unaligned images to compare gradcorr with ukbiobank gradcorr

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/ukbiobank-spinalcord-csa#12]
## Description :
To compare the results of gradient distorsion correction, the image corrected with the gradcorr of the pipeline using coeff.grad from Montreal Heart Institute was subtracted from the processed image of UK biobank. The spinal cord of the processed images of Uk biobank was cut off. To be able to subtract the images, the same transformation has to be done on the image with gradcorr of the pipeline. 

### Input data:
For T1w:
* The image `sub_1000032_T1w.nii.gz` was used, it corresponds to : `T1_orig_defaced.nii.gz` in ukbiobank database.
* The processed image of ukbiobank for the subject 1000032 is : `T1.nii.gz` in ukbiobank database
* The coeff.grad file used is from Montreal Heart Institute.

For T2w:
* The image `sub_1000032_T2w.nii.gz` was used, it corresponds to : `T2_FLAIR_orig_defaced.nii.gz` in ukbiobank database.
* The processed image of ukbiobank for the subject 1000032 is: `T2_FLAIR.nii.gz` in ukbiobank database
* The coeff.grad file used is from Montreal Heart Institute.

## Problems:
* While cropping the spinal cord of the gradcorr image with `sct_crop_image -i -ref T1.nii.gz` (see step 2 and 3 below), the shape of the output isn't the same as the ref (`T1.nii.gz`). 
    Output shape: T1w(161, 221,181), T2w(154, 222, 282)
    Ref shape: (162, 222, 182) for T1w and T2w
    So the subtraction of the images is impossible after. Maybe there is a better use of this function to fix this problem.

* The images are not aligned. So when subtracting them, we can see a gradient in the difference image, more obvious for T2w. (step 4). Maybe it is an artefact of the first problem. Or it could directly be the difference of the gradcorr with ICM and ukbiobank.

## Steps to reproduce:
Using:
* SCT v5.0.1 
* [gradunwrap v1.2.0](https://github.com/Washington-University/gradunwarp/tree/v1.2.0) for gradient correction
* [FSLeyes](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes) 

The sames steps were applided to T2w
1. Apply gradcorr with coeff.grad from Montreal Heart Institue and gradunwrap tool.
~~~
gradient_unwarp.py sub_1000032_T1w.nii.gz sub-1000032_T1w_gradcorr.nii.gz siemens -g coeff.grad -n
~~~

2. Crop gradcorr image with `sct_crop_image`. with ukbiobank processed image as `-ref`parameter.

~~~
sct_crop_image -i sub_1000032_T1w_gradcorr.nii.gz -o sub_1000032_T1w_gradcorr_crop.nii.gz -ref T1.nii.gz
~~~

3. Asjust the shapes.
The output file has now a shape of (161, 221,181)
`T1.nii.gz` file has a shape of (162, 222, 182)
The output file of `sct_crop_image` doesn't have the same shape as the ref `T1.nii.gz`. To adjsut this, in flseyes, I cropped the `T1.nii.gz` to the shape (161, 221,181) --> `T1_crop.nii.gz`. Maybe the non-alignment of the images after is an artefact of this operation. There is clearly a better solution for this problem.

4. Subtract images.
~~~
sct_math -i T1_crop.nii.gz  -o sub_1000032_T1w_diff_uk_ICM.nii.gz -sub sub_1000032_T1w_gradcorr_crop.nii.gz
~~~

## Results:
While looking at `T1w_crop.nii.gz` and at `sub_1000032_T1w_gradcorr_crop.nii.gz` in FSLeyes, we can see the non-alignment of the images. Here is the result of the subtraction:

![sub_1000032_T1w_diff_uk_ICM](https://user-images.githubusercontent.com/71230552/100525535-ae57b500-318f-11eb-81ad-9da0e612113b.png)
Other operations were done on the ukbiobank processed image, the image intensity and contrats are not the same as in the original image. 

The exact operation was done with T2w (T1 flair), here is the result:
![sub_1000032_T2w_diff_uk_ICM png](https://user-images.githubusercontent.com/71230552/100525669-916fb180-3190-11eb-8445-b50d0462968a.png)
The shape of T2 crop was this time: (154, 222,182) and for T2w processed: (162 ,222, 182). We can observe a more obvious gradient in the difference image.  While observing `T2_FLAIR.nii.gz`  and `sub_1000032_T2w.nii.gz` in FSLeyes, we can see that the brain and spinal cord are not aligned, they shifted.

**Comment by jcohenadad** [comment]
Closing because https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/issues/6#issuecomment-777748358
