### ISSUE TITLE
Change name of repository 

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/ukbiobank-spinalcord-csa#24]
Change repository's name from *Projet3* to something more meaningful. @jcohenadad is there a convention in the lab for git repo names?

**Comment by jcohenadad** [comment]
I think we should transfer the repository to the github/neuropoly organization (you will keep the ownership of course), as this is becoming an "official" project with long-term follow-up.

so, something like `ukbiobank-spinalcord-csa`?

**Comment by sandrinebedard** [comment]
> so, something like `ukbiobank-spinalcord-csa`?

Seems good!

**Comment by sandrinebedard** [comment]
> I think we should transfer the repository to the github/neuropoly organization (you will keep the ownership of course), as this is becoming an "official" project with long-term follow-up.

yes sure! How do we proceed for that?

**Comment by jcohenadad** [comment]
> yes sure! How do we proceed for that?

go to settings > options > transfer ownership
organization name: neuropoly

**Comment by sandrinebedard** [comment]
done!

**Comment by jcohenadad** [comment]
the repos name changed all right, but did you do the transfer?

**Comment by sandrinebedard** [comment]
yes I did the transfer too, I can try again if it didn't work

**Comment by jcohenadad** [comment]
hum, the transfer didn't seem to work, the repos is still under your organization:
![image](https://user-images.githubusercontent.com/2482071/104397646-3b29b880-551b-11eb-85f3-62ed503774bf.png)

**Comment by sandrinebedard** [comment]
It said *Transferring may be delayed until the new owner approves the transfer.* you should have been notified somhow I think, I can try again.

**Comment by sandrinebedard** [comment]
The name of the repository was changed and the repo was moved under *sct-pipeline*.
