### ISSUE TITLE
Replace FSLeyes with itk-snap for manual segmentation

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/ukbiobank-spinalcord-csa#33]
I've looked into using itk-snap instead of FSLeyes for manual segmentation. Here are my thoughts on it and experience while downloading it:

* We can open the GUI within  CLI, would replace FSLeys without any problem (integrate it in script [manual_correction.py](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/blob/master/pipeline_ukbiobank/cli/manual_correction.py))
#### Windows: 
Very easy to install, no problem, we can also open image and seg from the command line, so that is great.
#### Linux (WSL) : a little more complicated... 
Even if itk-snap works with windows, we use SCT within the script `manual_correction.py` for disc label and  also for qc, so it is most likely we have to use itk-snap with WLS. 

* To get the 3.8 version from the dowloaded .tar file, we need to add the ITK-snap binary to PATH variable. 
When running `itksnap` this occured:
~~~
/usr/local/itksnap-3.8.0/lib/snap-3.8.0/ITK-SNAP: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
~~~
I searched about it and found that this library is no longer available using in Ubuntu 16.10+  https://askubuntu.com/questions/895897/error-while-loading-shared-libraries-libpng12-so-0
So we have to manually install it, not great.
 
* There is also a package for linux (v3.6):
~~~
sudo apt install itksnap
~~~
But when running `itksnap`, there is an error, I found that running it with [`sudo itksnap`](https://groups.google.com/g/itksnap-users/c/Up5UKta6soY)  works. Not the best solution, it may also be more difficult to intergrate to `manual_correction.py` script.

So it seems also pretty complicated to integrate 😂, I did not try on MacOS, maybe the person doing manual segmentation will have it, I suppose the installation is also easy?!

I don't know what would be better between FSLeyes and itk-snap, maybe if the problem is solved with linux, it would be ok. However, we could just avoid using SCT for manual segmentation, and run the qc after for the hole batch (as it is already possible). That would be the easiest solution, but it may become confusing to seperate disc labeling,  segmentation and qc (with different dependencies).

**Comment by jcohenadad** [comment]
> So it seems also pretty complicated to integrate 😂, I did not try on MacOS, maybe the person doing manual segmentation will have it, I suppose the installation is also easy?!

indeed, super easy.

> However, we could just avoid using SCT for manual segmentation, and run the qc after for the hole batch (as it is already possible). 

👍 

> That would be the easiest solution, but it may become confusing to seperate disc labeling, segmentation and qc (with different dependencies).

It should be fine. Really the most time consuming is manual correction of the cord segmentation (1-3min per subject, vs. ~5s for disc labeling). So, if we recruit people from outside, it might be easier to isolate the cord segmentation correction pipeline for a windows-compatible solution.

**Comment by sandrinebedard** [comment]
Ok great! I agree, isolating cord segmentation correction seems like the best and easiest way for this!
