### ISSUE TITLE
Add a file that lists subjects to exclude

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/ukbiobank-spinalcord-csa#37]
### Context

Some data could be of bad quality. In that case we might want to exclude that subject. We need to keep track of subjects that are removed for this project. [Example of "subject to remove" file for the spine generic project](https://github.com/spine-generic/data-multi-subject/blob/master/exclude.yml).

### Suggestion

- Add a file: `exclude.yml` to this repository.
- Consider this file while generating the statistics.

**Comment by sandrinebedard** [comment]
Example of bad quality:
![image](https://user-images.githubusercontent.com/71230552/108890068-18d79000-75db-11eb-996f-689a864ef452.png)
