### ISSUE TITLE
Create derivative and json sidecar for QC-ed automatic segmentations

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/ukbiobank-spinalcord-csa#51]
## Context
SC segmentations that are manually qc-ed and that  don't need manual corrections need to be added to derivatives and a json sidecar needs to be created.

## Idea
 A way would be to adjust the script `manual_correction.py` and pass as an argument the list of files that need correction (as usual but the files would be exlcluded instead). The rest of the files would be added to derivatives folder and a json sidecar would be created. 

I would only make this available for segmentations since we don't automatically create disc labeling for C1-2, C2-3 and C3-4 as we do manually.

## Tasks

* Add flag to specify that the list from `-config` are the subjects to exclude
* Go through all images except exluded ones (ONLY T1w images)
* Add segmentation with suffix `-manual` to derivatives
* Create jsonsidecar
* Don't call function `correct_segmentation` where ITK-snap is opened

**Comment by sandrinebedard** [comment]
@jcohenadad do we want to also exclude from this images in [exclude.yml](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/blob/master/exclude.yml) ? or we still keep the segmentations from those images

**Comment by jcohenadad** [comment]
> @jcohenadad do we want to also exclude from this images in [exclude.yml](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/blob/master/exclude.yml) ? or we still keep the segmentations from those images

hum... good question. I would keep the images because in the future we might want to come up with a deep learning algorithm that finds "bad looking" images. So having the images and the exclude.yml file would be perfect to train such model

**Comment by sandrinebedard** [comment]
Ok great!
