### ISSUE TITLE
Select the right coeff.grad file for each patient in process_data.sh

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/ukbiobank-spinalcord-csa#6]
All the linear distorsion corrections are done with the coeff.grad file of the  Skyra from the Montreal Heart Institute in process_data.sh. 

 ## Description of the enhancement
The coeff.grad file used for the correction should be linked to each assesment center: Cheadle, Newcastle and Reading.
Field 54 - assessment center : gives the assessment center of the subject

**Comment by jcohenadad** [comment]
We now have the proper info about what scanner was used with what patient-- @alexfoias has the email and can follow up with that.

what needs to be done:
- add info in the TSV about the site
- contact the centers and ask for the **coeff.grad** file

**Comment by alexfoias** [comment]
I'll take care of it.

**Comment by sandrinebedard** [comment]
@alexfoias Did you have time to contact the centers?

**Comment by jcohenadad** [comment]
> @alexfoias Did you have time to contact the centers?

unfortunately UKB refuses to send us the contact information for each center :-(. So I guess the next step would be to find those email addresses ourselves and I can contact each individual assessment center. @alexfoias can you pls do this search for me? 👉  Google

**Comment by alexfoias** [comment]
I tried to find the email addresses for the centers on the internet, but I wasn't able to find this information. That is way I sent the email with the subject "Re: Question about T1 MRI dataset" on 19 Jan 2021. Maybe @sandrinebedard will be more lucky ?

**Comment by sandrinebedard** [comment]
I searched too and didn't find any contact info for the assessment centers...
I also searched to see if I could find some people who worked in the specific centers, but it was also inconclusive

**Comment by jcohenadad** [comment]
ok let me look-- could you please list the centers (and any useful info you already have on them)?

**Comment by sandrinebedard** [comment]
The four assessment centers for imaging are:
* Reading
    * Address: Unit 3B, Pincents Kiln Industrial Park, Pincents Kiln, Calcot, Theale, Reading RG31 7SD.
* Cheadle
    * Address: 1-2 Spectrum Way, Adswood, Stockport, SK3 0SA
    * Also Uk biobank coordinating center
* Bristol
   * Address: Unit G4b, Bolingbroke Way, Patchway, Bristol, BS34 6FE.
* Newcastle
    * Address: Unit 2, Hawick Crescent Industrial Estate, Newcastle upon Tyne NE6 1AS


All the centers are in industrial parks or random spots like that. 
The only phone number I found for the assessment centers was this phone number for the Participant Resource Centre : +44 800 027 6276

I tried searching for a manager or something of each of the assessment centers, it was inconclusive, but I thought  maybe the chief operating officer could be a useful contact (" responsible for our Estate and Technical Services, Laboratory, Access and Study Administration teams and Health and Safety.") 
John Busby: john.busby@ukbiobank.ac.uk

I didn't know what else to search for after that!

**Comment by sandrinebedard** [comment]
I got a response from Daniel who asked around at Oxford, we got two names:
- Karla Miller karla.miller@ndcn.ox.ac.uk
- Steve Smith steve@fmrib.ox.ac.uk
Daniel told me they both helped setting the hole thing up and are implicated on the MRI part.

@jcohenadad do you prefer contacting them yourself? (or I can also do it)

**Comment by jcohenadad** [comment]
i know them, I'll contact them 👍

**Comment by jcohenadad** [comment]
Comparing the coeff.grad files from MHI and CHUM, they are exactly the same. This led us assume that all Skyra systems are using the same coeff.grad file, and hence there is no need for fetching site-specific file anymore.

**Comment by alexfoias** [comment]
great news.
