### ISSUE TITLE
coeff.grad discussion

### ISSUE THREAD

**Issue by alexfoias** [sct-pipeline/ukbiobank-spinalcord-csa#7]
I generated the list of centres (based on the subjects that have all 3 MRI modalities) based on the information suggested (field 54 - assessment centre) by the UKBiobank. The resulted list has all centres listed here: https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=54 (without Bristol). 

Then I analyzed the document explaining the protocol: https://biobank.ndph.ox.ac.uk/showcase/showcase/docs/brain_mri.pdf. In this document they state that the imaging took place at Cheadle Manchester, Newcastle and Reading on a Siemens Skyra 3T running VD13A SP4. 

Conclusion: I think the assessment center might be different from the imaging center. We would have to ask Siemens for the grad.coeff for the locations Cheadle Manchester, Newcastle and Reading. I did a follow-up with the UKBiobank to see where can I find the information linking the subjects with the imaging center and assessment center.

**Comment by jcohenadad** [comment]
Closing because of https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/issues/6#issuecomment-777748358
