### ISSUE TITLE
How to get coeff.grad file

### ISSUE THREAD

**Issue by karllandheer** [sct-pipeline/ukbiobank-spinalcord-csa#86]
Hello, this isn't necessarily an issue with your package, but it seems from some issues you guys have encountered this issue so I will ask it here. How did you get the UK biobank Siemens coeff.grad file? Did you contact fMRIB or UKB directly and ask?

**Comment by jcohenadad** [comment]
no, we used the coeff.grad file from another institution with the same scanner gradient model (according to siemens, the coeff.grad file is the same)

**Comment by karllandheer** [comment]
I see, and I presume you are not allowed to distribute this?

**Comment by jcohenadad** [comment]
> I see, and I presume you are not allowed to distribute this?

unfortunately not
